// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Models
{
    public partial class uspGetManagerEmployeesResult
    {
        public int? RecursionLevel { get; set; }
        [StringLength(4000)]
        public string OrganizationNode { get; set; }
        [StringLength(50)]
        public string ManagerFirstName { get; set; }
        [StringLength(50)]
        public string ManagerLastName { get; set; }
        public int? BusinessEntityID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
    }
}
