// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AdventureWorks.DbDatas;
using AdventureWorks.Entities;
using AdventureWorks.Entities.dboSchema;
using AdventureWorks.Entities.HumanResourcesSchema;
using AdventureWorks.Entities.PersonSchema;
using AdventureWorks.Entities.ProductionSchema;
using AdventureWorks.Entities.PurchasingSchema;
using AdventureWorks.Entities.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace AdventureWorks.DbDatas.Configurations
{
    public partial class ProductDocumentConfiguration : IEntityTypeConfiguration<ProductDocument>
    {
        public void Configure(EntityTypeBuilder<ProductDocument> entity)
        {
            entity.HasKey(e => new { e.ProductID, e.DocumentNode }).HasName("PK_ProductDocument_ProductID_DocumentNode");

            entity.ToTable("ProductDocument", "Production", tb => tb.HasComment("Cross-reference table mapping products to related product documents."));

            entity.Property(e => e.ProductID).HasComment("Product identification number. Foreign key to Product.ProductID.");
            entity.Property(e => e.DocumentNode).HasComment("Document identification number. Foreign key to Document.DocumentNode.");
            entity.Property(e => e.ModifiedDate)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Date and time the record was last updated.");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductDocument> entity);
    }
}
