// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AdventureWorks.Data;
using AdventureWorks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AdventureWorks.Data.Configurations
{
    public partial class vProductAndDescriptionConfiguration : IEntityTypeConfiguration<vProductAndDescription>
    {
        public void Configure(EntityTypeBuilder<vProductAndDescription> entity)
        {
            entity.ToView("vProductAndDescription", "Production");

            entity.Property(e => e.CultureID).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<vProductAndDescription> entity);
    }
}
