// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AdventureWorks.Data;
using AdventureWorks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AdventureWorks.Data.Configurations
{
    public partial class vStateProvinceCountryRegionConfiguration : IEntityTypeConfiguration<vStateProvinceCountryRegion>
    {
        public void Configure(EntityTypeBuilder<vStateProvinceCountryRegion> entity)
        {
            entity.ToView("vStateProvinceCountryRegion", "Person");

            entity.Property(e => e.StateProvinceCode).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<vStateProvinceCountryRegion> entity);
    }
}
