// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AdventureWorks.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AdventureWorks.Data
{
    public partial interface IAdventureWorksContextProcedures
    {
        Task<List<uspGetBillOfMaterialsResult>> uspGetBillOfMaterialsAsync(int? startProductID, DateTime? checkDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetEmployeeManagersResult>> uspGetEmployeeManagersAsync(int? businessEntityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetManagerEmployeesResult>> uspGetManagerEmployeesAsync(int? businessEntityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetWhereUsedProductIDResult>> uspGetWhereUsedProductIDAsync(int? startProductID, DateTime? checkDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspLogErrorAsync(OutputParameter<int?> errorLogID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspPrintErrorAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspSearchCandidateResumesResult>> uspSearchCandidateResumesAsync(string searchString, bool? useInflectional, bool? useThesaurus, int? language, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspUpdateEmployeeHireInfoAsync(int? businessEntityID, string jobTitle, DateTime? hireDate, DateTime? rateChangeDate, decimal? rate, byte? payFrequency, bool? currentFlag, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspUpdateEmployeeLoginAsync(int? businessEntityID, byte[] organizationNode, string loginID, string jobTitle, DateTime? hireDate, bool? currentFlag, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspUpdateEmployeePersonalInfoAsync(int? businessEntityID, string nationalIDNumber, DateTime? birthDate, string maritalStatus, string gender, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
