// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Models
{
    public partial class ufnGetContactInformationResult
    {
        public int PersonID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string JobTitle { get; set; }
        [StringLength(50)]
        public string BusinessEntityType { get; set; }
    }
}
